spring:
  application:
    name: "2.2.2"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

loan:
  minimalIncome: 40000
  minimalCarPrice: 1000000
  url: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income